sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        groups:
            users_group:
                label: 'Users'
                icon: '<i class="fa fa-users"></i>'
                items:
                    - app.admin.user
            products_group:
                label: 'Products'
                icon: '<i class="fa fa-product-hunt"></i>'
                items:
                    - app.admin.product

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
