version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kabel_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - kabelrf

  nginx:
    image: nginx:1.21
    container_name: kabel_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - kabelrf

  db:
    image: mariadb:11.3.2
    command: --default-authentication-plugin=mysql_native_password
    container_name: kabel_db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-db_password}
      MYSQL_DATABASE: ${DB_NAME:-db_name}
      MYSQL_USER: ${DB_USERNAME:-db_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-db_password}
    networks:
      - kabelrf

networks:
  kabelrf:

volumes:
  db:
