#index:
#    path: /
#    controller: App\Controller\DefaultController::index
sonata_admin_redirect:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: 'sonata_admin_dashboard'
    permanent: true
